### ISSUE TITLE
HSET does not support multiple field values 

### ISSUE THREAD

**Issue by Rajat-Goyal** [go-redis/redis#1242]
I think the the HSET should currently support multiple field-value pairs.
 
As I can see, since HMSet has been deprecated the library has started using HSet underneath HMSet. But, the HSet still does not support more than single field and value. 
We should also change/enhance the library's HSet to be able to do the same by making it possible to send multiple field value pairs. 

The library should reflect redis documentation for HSET. Or is there a reason that we have still kept it like this?

**Comment by vmihailenco** [comment]
Did you see https://github.com/go-redis/redis/blob/master/commands.go#L986-L989 ? It shows how to use HMSet.

**Comment by Rajat-Goyal** [comment]
Yes I saw this. What i am saying is that HMSET is deprecated and we do keep it to support folks who are still using HMSET which is a good thing. But library's HSET abstraction does not reflect the the spec from redis since we cannot pass multiple field value pairs as mentioned here https://redis.io/commands/hset
`As of Redis 4.0.0, HSET is variadic and allows for multiple field/value pairs.` 
I am just saying we should enhance the HSet abstraction to support this ^ 
HMSet abstraction can help me achieve it correct; but, I should be able to use HSET as per the specs.

**Comment by vmihailenco** [comment]
Go method `HMSet` uses Redis `HSet` internally - so just continue to use `rdb.HMSet` - it uses correct Redis API.

**Comment by Rajat-Goyal** [comment]
I don't think i am able to explain it correctly what my concern was 
1. HMSet there to support old codes that use HMSet [**Good**] 
2. HMSet internally uses HSet [**Good**]
3. HSet can only take a single field value [**Not Good**]

If the redis documentation says we can send multiple field value pairs for single hashKey using HSet I should be able to do that with this library's HSet also. Why should I use HMSet in a new codebase only because I want to send multiple field value pairs.

**Comment by vmihailenco** [comment]
I decided to keep both `HSet` and `HMSet` Go API (not Redis API), because that preserves backwards compatibility *and* provides API that supports both single and multiple fields in sensible way. There is some confusion but no real harm in that.

If you have an idea how to make `HSet` support both single and multiple fields in a nice and usable way - please show it.

**Comment by pavanyewale** [comment]
Hi guys, I have solve this issue and make a pull request please see it #1245

**Comment by Rajat-Goyal** [comment]
@pavanyewale if we are to match the spec the response will change from BoolCmd to IntCmd since HSet returns an integer reply. ref: https://redis.io/commands/hset 

@vmihailenco  This PR reflects what i was mentioning #1246 
Let me know if I have missed out seeing something.

P.S:  I had to rely mostly on travis build to check for tests passing correctly. I wasn't able to build this on my local machine (MacOS Catalina 10.15) I think we should have Contributing.md so that people can build and test locally with more ease.

**Comment by pavanyewale** [comment]
@Rajat-Goyal  but if you now change response from BoolCmd to IntCmd how it supports backword compatibility?

**Comment by Rajat-Goyal** [comment]
It would be Kind of a breaking change correct but since IntCmd and BoolCmd all have same functions like Val and Err I assume it shouldn’t be that big an impact. 

However if we don’t have something like IntCmd I can never get something like how many keys were added. 

Moreover since the step is in the right direction I think we should still go ahead with this.

**Comment by Rajat-Goyal** [comment]
Resolved with https://github.com/go-redis/redis/pull/1263. Closing

**Comment by alidehghan** [comment]
I am using github.com/go-redis/redis/v8 v8.11.5 and this issue still remains unresolved. just send one field.
